server:
  port: 9000

spring:
  application:
    name: venus-platform-api
    clientUrl: http://localhost:3000
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    cache-names: venus-platform-api
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://tyke.db.elephantsql.com/yrkunwuf
    username: yrkunwuf
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: venus-plataform
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true

jwt:
  secret: ${JWT_SECRET}
  issuer: venus.com
